/*
 * Copyright 2026 Sharexpress Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { API } from "@/api/api";

// Public, read-only view of a shared interview report (no auth required).
export default function SharedReport() {
  const { token } = useParams();
  const [data, setData] = useState(null);
  const [status, setStatus] = useState("loading"); // loading | ok | error

  useEffect(() => {
    let alive = true;
    API.get(`/interview/shared/${token}`)
      .then((res) => {
        if (alive) {
          setData(res.data);
          setStatus("ok");
        }
      })
      .catch(() => {
        if (alive) setStatus("error");
      });
    return () => {
      alive = false;
    };
  }, [token]);

  if (status === "loading") return <Centered>Loading shared report…</Centered>;
  if (status === "error")
    return <Centered>This shared report was not found or is no longer available.</Centered>;

  const report = data.report || data;
  const role = data.role || report.role || "Interview";
  const overall = Math.round(
    report.overall_score ??
      report.score ??
      (report.average_score ? report.average_score * 10 : 0)
  );
  const strengths = report.strengths || [];
  const improvements =
    report.improvements || report.areas_for_improvement || report.concerns || [];
  const topics = report.topic_evaluations || [];

  const scoreColor =
    overall >= 75 ? "#f97316" : overall >= 55 ? "#eab308" : "#ef4444";

  return (
    <div className="min-h-screen bg-black text-zinc-100 py-10 px-4">
      <div className="mx-auto max-w-3xl space-y-6">
        <header className="space-y-1">
          <p className="text-xs uppercase tracking-widest text-orange-500 font-mono">
            Shared Interview Report
          </p>
          <h1 className="text-2xl font-bold">{role}</h1>
          {data.created_at && (
            <p className="text-sm text-zinc-500">
              {new Date(data.created_at).toLocaleDateString()}
            </p>
          )}
        </header>

        <div className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-6 flex items-center gap-6">
          <div className="text-5xl font-bold" style={{ color: scoreColor }}>
            {overall}
            <span className="text-lg text-zinc-500">/100</span>
          </div>
          <p className="text-zinc-400">Overall performance score</p>
        </div>

        {strengths.length > 0 && <Section title="Strengths" items={strengths} />}
        {improvements.length > 0 && (
          <Section title="Areas to improve" items={improvements} />
        )}

        {topics.length > 0 && (
          <div className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-6">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-400 mb-3">
              Topic breakdown
            </h2>
            <div className="space-y-2">
              {topics.map((t, i) => (
                <div key={i} className="flex items-start gap-3">
                  <span className="shrink-0 rounded bg-zinc-800 px-2 py-0.5 text-xs font-mono">
                    {t.score ?? "-"}/10
                  </span>
                  <div>
                    <p className="text-sm font-medium">{t.topic}</p>
                    {t.summary && (
                      <p className="text-xs text-zinc-500">{t.summary}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        <footer className="pt-4 text-center text-xs text-zinc-600">
          Generated by InterLeet ·{" "}
          <a href="/" className="underline">
            interleet.sharexpress.in
          </a>
        </footer>
      </div>
    </div>
  );
}

function Centered({ children }) {
  return (
    <div className="min-h-screen bg-black text-zinc-300 flex items-center justify-center px-4 text-center">
      {children}
    </div>
  );
}

function Section({ title, items }) {
  return (
    <div className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-6">
      <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-400 mb-3">
        {title}
      </h2>
      <ul className="list-disc pl-5 space-y-1 text-sm text-zinc-300">
        {items.map((s, i) => (
          <li key={i}>
            {typeof s === "string" ? s : s.text || s.summary || JSON.stringify(s)}
          </li>
        ))}
      </ul>
    </div>
  );
}
