/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSystemDesignRouteImport } from './routes/app/system-design'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppLeaderboardRouteImport } from './routes/app/leaderboard'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppInterviewsIndexRouteImport } from './routes/app/interviews/index'
import { Route as AppChallengesIndexRouteImport } from './routes/app/challenges/index'
import { Route as AppProfileUsernameRouteImport } from './routes/app/profile/$username'
import { Route as AppInterviewsLiveRouteImport } from './routes/app/interviews/live'
import { Route as AppEditorIdRouteImport } from './routes/app/editor.$id'
import { Route as AppChallengesIdRouteImport } from './routes/app/challenges/$id'
import { Route as AppInterviewsIdReportRouteImport } from './routes/app/interviews/$id.report'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSystemDesignRoute = AppSystemDesignRouteImport.update({
  id: '/app/system-design',
  path: '/app/system-design',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/app/leaderboard',
  path: '/app/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInterviewsIndexRoute = AppInterviewsIndexRouteImport.update({
  id: '/app/interviews/',
  path: '/app/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChallengesIndexRoute = AppChallengesIndexRouteImport.update({
  id: '/app/challenges/',
  path: '/app/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileUsernameRoute = AppProfileUsernameRouteImport.update({
  id: '/app/profile/$username',
  path: '/app/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInterviewsLiveRoute = AppInterviewsLiveRouteImport.update({
  id: '/app/interviews/live',
  path: '/app/interviews/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEditorIdRoute = AppEditorIdRouteImport.update({
  id: '/app/editor/$id',
  path: '/app/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChallengesIdRoute = AppChallengesIdRouteImport.update({
  id: '/app/challenges/$id',
  path: '/app/challenges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInterviewsIdReportRoute = AppInterviewsIdReportRouteImport.update({
  id: '/app/interviews/$id/report',
  path: '/app/interviews/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/recruiter': typeof RecruiterRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/system-design': typeof AppSystemDesignRoute
  '/app/challenges/$id': typeof AppChallengesIdRoute
  '/app/editor/$id': typeof AppEditorIdRoute
  '/app/interviews/live': typeof AppInterviewsLiveRoute
  '/app/profile/$username': typeof AppProfileUsernameRoute
  '/app/challenges/': typeof AppChallengesIndexRoute
  '/app/interviews/': typeof AppInterviewsIndexRoute
  '/app/interviews/$id/report': typeof AppInterviewsIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/recruiter': typeof RecruiterRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/system-design': typeof AppSystemDesignRoute
  '/app/challenges/$id': typeof AppChallengesIdRoute
  '/app/editor/$id': typeof AppEditorIdRoute
  '/app/interviews/live': typeof AppInterviewsLiveRoute
  '/app/profile/$username': typeof AppProfileUsernameRoute
  '/app/challenges': typeof AppChallengesIndexRoute
  '/app/interviews': typeof AppInterviewsIndexRoute
  '/app/interviews/$id/report': typeof AppInterviewsIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/recruiter': typeof RecruiterRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/system-design': typeof AppSystemDesignRoute
  '/app/challenges/$id': typeof AppChallengesIdRoute
  '/app/editor/$id': typeof AppEditorIdRoute
  '/app/interviews/live': typeof AppInterviewsLiveRoute
  '/app/profile/$username': typeof AppProfileUsernameRoute
  '/app/challenges/': typeof AppChallengesIndexRoute
  '/app/interviews/': typeof AppInterviewsIndexRoute
  '/app/interviews/$id/report': typeof AppInterviewsIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot'
    | '/login'
    | '/recruiter'
    | '/signup'
    | '/app/dashboard'
    | '/app/leaderboard'
    | '/app/settings'
    | '/app/system-design'
    | '/app/challenges/$id'
    | '/app/editor/$id'
    | '/app/interviews/live'
    | '/app/profile/$username'
    | '/app/challenges/'
    | '/app/interviews/'
    | '/app/interviews/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot'
    | '/login'
    | '/recruiter'
    | '/signup'
    | '/app/dashboard'
    | '/app/leaderboard'
    | '/app/settings'
    | '/app/system-design'
    | '/app/challenges/$id'
    | '/app/editor/$id'
    | '/app/interviews/live'
    | '/app/profile/$username'
    | '/app/challenges'
    | '/app/interviews'
    | '/app/interviews/$id/report'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot'
    | '/login'
    | '/recruiter'
    | '/signup'
    | '/app/dashboard'
    | '/app/leaderboard'
    | '/app/settings'
    | '/app/system-design'
    | '/app/challenges/$id'
    | '/app/editor/$id'
    | '/app/interviews/live'
    | '/app/profile/$username'
    | '/app/challenges/'
    | '/app/interviews/'
    | '/app/interviews/$id/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  RecruiterRoute: typeof RecruiterRoute
  SignupRoute: typeof SignupRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSystemDesignRoute: typeof AppSystemDesignRoute
  AppChallengesIdRoute: typeof AppChallengesIdRoute
  AppEditorIdRoute: typeof AppEditorIdRoute
  AppInterviewsLiveRoute: typeof AppInterviewsLiveRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
  AppChallengesIndexRoute: typeof AppChallengesIndexRoute
  AppInterviewsIndexRoute: typeof AppInterviewsIndexRoute
  AppInterviewsIdReportRoute: typeof AppInterviewsIdReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/system-design': {
      id: '/app/system-design'
      path: '/app/system-design'
      fullPath: '/app/system-design'
      preLoaderRoute: typeof AppSystemDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/app/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/interviews/': {
      id: '/app/interviews/'
      path: '/app/interviews'
      fullPath: '/app/interviews/'
      preLoaderRoute: typeof AppInterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/challenges/': {
      id: '/app/challenges/'
      path: '/app/challenges'
      fullPath: '/app/challenges/'
      preLoaderRoute: typeof AppChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/$username': {
      id: '/app/profile/$username'
      path: '/app/profile/$username'
      fullPath: '/app/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/interviews/live': {
      id: '/app/interviews/live'
      path: '/app/interviews/live'
      fullPath: '/app/interviews/live'
      preLoaderRoute: typeof AppInterviewsLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/editor/$id': {
      id: '/app/editor/$id'
      path: '/app/editor/$id'
      fullPath: '/app/editor/$id'
      preLoaderRoute: typeof AppEditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/challenges/$id': {
      id: '/app/challenges/$id'
      path: '/app/challenges/$id'
      fullPath: '/app/challenges/$id'
      preLoaderRoute: typeof AppChallengesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/interviews/$id/report': {
      id: '/app/interviews/$id/report'
      path: '/app/interviews/$id/report'
      fullPath: '/app/interviews/$id/report'
      preLoaderRoute: typeof AppInterviewsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  RecruiterRoute: RecruiterRoute,
  SignupRoute: SignupRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSystemDesignRoute: AppSystemDesignRoute,
  AppChallengesIdRoute: AppChallengesIdRoute,
  AppEditorIdRoute: AppEditorIdRoute,
  AppInterviewsLiveRoute: AppInterviewsLiveRoute,
  AppProfileUsernameRoute: AppProfileUsernameRoute,
  AppChallengesIndexRoute: AppChallengesIndexRoute,
  AppInterviewsIndexRoute: AppInterviewsIndexRoute,
  AppInterviewsIdReportRoute: AppInterviewsIdReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
